### PR TITLE
add first rice-box

### PR DESCRIPTION
**Pull request by hacdias**
@1138-4EB take a look!

### CODE REVIEW

**Comment by hacdias** [comment]
Tested a build and it works. This is really nice 😄

**Comment by 1138-4EB** [comment]
LGTM. However, I think we should:

- Use docker image `filebrowser/dev` (probably renamed to `filebrowser/devenv`), in order to:
  - Avoid installing `gomeralinter` every time.
  - Provide/use a portable workflow that developers/contributors can reproduce locally.
- Build caddy with all the three plugins in a travis stage. This would ensure that the integration works, and not only that these can be build as a library.

**Comment by hacdias** [comment]
@1138-4EB is that about the build process? If so, it can be done on another PR

**Comment by 1138-4EB** [comment]
Yes. I'll open a new PR after I fix filebrowser/filebrowser.

**Pull request merged**
